name: Cassette rerecord

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Variable setup
        id: variables
        run: echo "DATE=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
      - name: Checkout cassettes branch
        run: git checkout -b ${{ steps.variables.outputs.DATE }}-cassette-re-record
      - name: Restore dependencies
        run: dotnet restore
      - name: Delete cassettes
        run: rm -rf VCR.Demo.IntegrationTests/Cassettes
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Commit changes
        run: |
          git config --global user.name 'Cassette Bot'
          git config --global user.email 'thomas-mullaly@users.noreply.github.com'
          git commit -am "Automated cassette recording"
          git push --set-upstream origin $(git branch --show-current)
      - name: Push and create PR
        run: gh pr create --title "${{ steps.variables.outputs.DATE }} Automated cassette recording" --body "Automated cassette recording"
        env:
          GH_TOKEN: ${{ github.token }}