name: Cassette rerecord

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Variable setup
        id: variables
        run: echo "PR_DATE=$(date +"%Y-%m-%d")" >> "$GITHUB_ENV"
      - name: Checkout cassettes branch
        run: git checkout -b ${{ env.PR_DATE }}-${{ github.run_number }}-cassette-re-record
      - name: Restore dependencies
        run: dotnet restore
      - name: Delete cassettes
        run: rm -rf VCR.Demo.IntegrationTests/Cassettes
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
        env:
          DONKI_KEY: ${{ secrets.DONKI_KEY }}
          NEO_KEY: ${{ secrets.NEO_KEY }}
      - name: Commit changes
        run: |
          git config --global user.name 'Cassette Bot'
          git config --global user.email 'thomas-mullaly@users.noreply.github.com'
          git commit -am "Automated cassette recording"
          git push --set-upstream origin $(git branch --show-current)
      - name: Push and create PR
        run: gh pr create --title "${{ env.PR_DATE }} Automated cassette recording" --body "Automated cassette recording"
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}